
OBJECTS = proj3.c inserepeca.c tetris.c espacojogo.c determinalinha.c lststrops.c heap.c hash.c tabsim.c pecaops.c selection.c
CCFLAGS = -ansi -pedantic -Wall -g
EXEC    = proj3

all: $(OBJECTS)
	gcc $(CCFLAGS) $(OBJECTS) -o $(EXEC)

